name: Deploy version

on:
  push:
    tags: v*.*.*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Deploy
      uses: matthewp/cdn-spooky-deploy-action@v1
      with:
        pkg: 'beach'