name: Deploy version

on:
  push:
    tags: v*.*.*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set tag
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set version
      run: |
        id=$(echo "$RELEASE_TAG" | cut -dv -f2)
        echo "RELEASE_VERSION=$id" >> $GITHUB_ENV
    - name: Set folder
      run |
        folder=$(echo "beach/$RELEASE_VERSION")
        echo "RELEASE_FOLDER=$folder" >> $GITHUB_ENV
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east1'
          SOURCE_DIR: 'lib'
          DEST_DIR: "$RELEASE_FOLDER"